In [1]:
import pandas as pd

In [3]:
df=pd.read_csv(r"D:\Datasets\cleaned_retail_data_updatedw3.csv")

In [4]:
df.info

<bound method DataFrame.info of         InvoiceNo StockCode                          Description  Quantity  \
0          536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1          536365     71053                  WHITE METAL LANTERN         6
2          536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3          536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4          536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...           ...       ...                                  ...       ...
392687     581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
392688     581587     22899         CHILDREN'S APRON DOLLY GIRL          6
392689     581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
392690     581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
392691     581587     22138        BAKING SET 9 PIECE RETROSPOT          3

             InvoiceDate  UnitPrice  CustomerID         Country  \
0       01-12-2010 08:26       2.55       17850  United Kingdom
1       01-12-2010 08:26       3.39       17850  United Kingdom
2       01-12-2010 08:26       2.75       17850  United Kingdom
3       01-12-2010 08:26       3.39       17850  United Kingdom
4       01-12-2010 08:26       3.39       17850  United Kingdom
...                  ...        ...         ...             ...
392687  09-12-2011 12:50       0.85       12680          France
392688  09-12-2011 12:50       2.10       12680          France
392689  09-12-2011 12:50       4.15       12680          France
392690  09-12-2011 12:50       4.15       12680          France
392691  09-12-2011 12:50       4.95       12680          France

       TransactionMonth CohortMonth  CohortIndex
0            01-12-2010  01-12-2010          0.0
1            01-12-2010  01-12-2010          0.0
2            01-12-2010  01-12-2010          0.0
3            01-12-2010  01-12-2010          0.0
4            01-12-2010  01-12-2010          0.0
...                 ...         ...          ...
392687       01-12-2011  01-09-2011          3.0
392688       01-12-2011  01-09-2011          3.0
392689       01-12-2011  01-09-2011          3.0
392690       01-12-2011  01-09-2011          3.0
392691       01-12-2011  01-09-2011          3.0

[392692 rows x 11 columns]>

In [5]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TransactionMonth,CohortMonth,CohortIndex
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850,United Kingdom,01-12-2010,01-12-2010,0.0
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850,United Kingdom,01-12-2010,01-12-2010,0.0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850,United Kingdom,01-12-2010,01-12-2010,0.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850,United Kingdom,01-12-2010,01-12-2010,0.0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850,United Kingdom,01-12-2010,01-12-2010,0.0

In [6]:
df["Total Revenue"]=df["Quantity"]*df["UnitPrice"]

In [8]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TransactionMonth,CohortMonth,CohortIndex,Total Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850,United Kingdom,01-12-2010,01-12-2010,0.0,15.30
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850,United Kingdom,01-12-2010,01-12-2010,0.0,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850,United Kingdom,01-12-2010,01-12-2010,0.0,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850,United Kingdom,01-12-2010,01-12-2010,0.0,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850,United Kingdom,01-12-2010,01-12-2010,0.0,20.34

In [10]:
customer_revenue=df.groupby("CustomerID")["Total Revenue"].sum().reset_index()
print(customer_revenue.head())

   CustomerID  Total Revenue
0       12346       77183.60
1       12347        4310.00
2       12348        1797.24
3       12349        1757.55
4       12350         334.40

In [12]:
df.to_csv("D:/Datasets/cleaned_retail_data_updatedw3.csv", index=False)